trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python311:
      python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    cd Sample_Selenium
    pip install selenium==3.14.0
    python index2.py
  displayName: 'Run Selenium Script'