trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python311:
      python.version: '3.11.4'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    cd sample_selenium_win
    pip install selenium==3.14.0
    pip install pytest==6.2.5
    python index2.py
  displayName: 'Run Selenium Script'