name: Selenium Test

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4  # Use the desired Python version

      - name: Install Dependencies
        run: |
          pip install selenium==3.141.0
          pip install webdriver_manager==3.8.6
          pip install pytest==6.2.5

      - name: Run Selenium Test
        run: |
          cd smart_ui_desktop
          python test.py  # Replace with the actual filename
        
