name: Selenium Tests

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  selenium_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11 # You can change the Python version if needed

    - name: Install dependencies
      run: |
        cd smart_ui_desktop
        pip install selenium==3.141.0
        pip install pytest
        python test.py

    
